//
// CatFactStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct CatFactStatus: Codable {

    public var verified: Bool?
    public var feedback: String?
    public var sentCount: Double?

    public init(verified: Bool? = nil, feedback: String? = nil, sentCount: Double? = nil) {
        self.verified = verified
        self.feedback = feedback
        self.sentCount = sentCount
    }

}

