//
// CatFact.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct CatFact: Codable {

    public var status: CatFactStatus
    public var type: String
    public var deleted: Bool?
    public var id: String
    public var user: String?
    public var text: String
    public var v: Double?
    public var source: String?
    public var updatedAt: String?
    public var createdAt: String?
    public var used: Bool?

    public init(status: CatFactStatus, type: String, deleted: Bool? = nil, id: String, user: String? = nil, text: String, v: Double? = nil, source: String? = nil, updatedAt: String? = nil, createdAt: String? = nil, used: Bool? = nil) {
        self.status = status
        self.type = type
        self.deleted = deleted
        self.id = id
        self.user = user
        self.text = text
        self.v = v
        self.source = source
        self.updatedAt = updatedAt
        self.createdAt = createdAt
        self.used = used
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case status
        case type
        case deleted
        case id = "_id"
        case user
        case text
        case v = "__v"
        case source
        case updatedAt
        case createdAt
        case used
    }

}

